### ISSUE TITLE
Order of Connector Results

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#135]
The idea of searching material in existing lists seems sensible, but we are finding that the search can't handle phrases. In our sandbox version at BCU, if I search for "Tort Law", the Capita Connector returns this as a phrase (so the results are relevant), while the search across existing lists is just finding items with little relevance (in this case a book written by an author called Tortora). I've attached an example.

Can the catalogue results be first in the list, or can the search across the existing lists be turned off?
[Phrase Search.docx](https://github.com/PTFS-Europe/rebus-list-2/files/341771/Phrase.Search.docx)

**Comment by mrenvoize** [comment]
Great feedback Paul. 

 It's high on my list to improve the existing materials search results as they're somewhat hit and miss at the moment.  

The idea of shifting off the local results hadn't really occurred to me before, but actually it's not a bad idea.  We're matching materials on connector ids at the server anyway do duplication should still be avoided.

In short, I'm on the case.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#1878

**Comment by mrenvoize** [comment]
Update on this:
- [x] Phrase search is now working #178
- [x] Stopwords are now implemented #175 
- [x] Filter out non-local materials #202 
- [x] Search result ordering is scheduled #179

**Comment by mrenvoize** [comment]
I've just added a 'filter out non-local materials' to the above list, that should go some way towards hiding the local results form view until absolutely necessary. 

This is a quicker win than delving into the code for allowing the 'local' results to appear in a different order, and should go a long way to achieving the same goals (We are still intending on allowing the order to be chosen too as a next step after filtering)

**Comment by mrenvoize** [comment]
Please also see our recent [blog post](https://ptfs-europe.github.io/rebus-list/update/2016/08/16/Add_item.html)

**Comment by fionaborthwick1** [comment]
Just to add a comment to this one.... when I was at Sunderland for a meeting yesterday, we were discussing the concept of 'local items' and I was asked if it was possible to remove this search or alternatively move the search results to the bottom of the connector results.  I informed them that this was already on our issues but thought that putting their comments here would also help.

**Comment by AndrewIsh** [comment]
It is already possible to move local results to the bottom of the results set. This was done as part of the BCU requirements.

**Comment by fionaborthwick1** [comment]
Could you do that for Sunderland at some point then too please @AndrewIsh? Thanks!

**Comment by AndrewIsh** [comment]
Done

**Comment by AndrewIsh** [comment]
Done and done
